export const GENRE_OPTIONS = [
  'Fantasy',
  'Science Fiction',
  'Mystery',
  'Thriller',
  'Romance',
  'Historical Fiction',
  'Non-fiction',
  'Biography',
  'Self-help',
  'Young Adult',
  'Horror',
  'Poetry',
  'Graphic Novel',
  'Classics',
  'Adventure',
  'Crime',
  'Philosophy',
  'Essays',
];
